import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


from time import sleep
from random import random
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains


googledoc_link = "https://docs.google.com/document/d/15paPCKRfY6g1RDpONlvHuErdmgA7VIJx_UQYaIuaiQs/edit"


TEXT = """AI refers to the simulation of human intelligence processes by machines, primarily computer systems. It encompasses a range of technologies, including machine learning, natural language processing, and robotics. Over the past few decades, AI has evolved from a theoretical concept to a practical tool that permeates various sectors of the economy. From automated assembly lines in factories to personalized recommendations on streaming platforms, AI has become ubiquitous, shaping how businesses operate and how individuals interact with technology.
AI should be made a public good, specifically in the form of Universal Basic Income (UBI), to address socio-economic inequalities. UBI, a concept rooted in providing every citizen with a regular and unconditional cash payment, regardless of their employment status, is gaining traction as a potential solution to the challenges posed by AI-driven automation and rising inequality.
UBI is a form of social security that guarantees a certain level of income to every citizen within a given geographic area, without means testing or work requirements. It aims to ensure a basic standard of living and alleviate poverty by providing individuals with financial security and autonomy.
Socio-economic inequality has reached staggering levels globally. According to the World Inequality Report 2022, the top 1% of wealth holders captured 27% of global wealth growth from 1980 to 2020, while the bottom 50% saw their wealth share decline. This concentration of wealth at the top exacerbates disparities in access to education, healthcare, and opportunities for social mobility.
Deepening inequality not only harms individuals but also weakens social cohesion and economic stability. Studies have shown that societies with high levels of inequality experience higher rates of crime, lower life expectancy, and reduced trust in institutions. By addressing inequality through UBI, we can promote greater equality of opportunity and enhance overall well-being.
The advent of AI and automation has reshaped the labor market, leading to concerns about job displacement and unemployment. Historical data and recent trends indicate that AI technologies have already replaced or augmented human labor in sectors such as manufacturing, transportation, and customer service.
Forecasts suggest that AI will continue to disrupt traditional employment patterns, with routine tasks being most susceptible to automation. A study by the OECD estimates that 14% of jobs in developed countries are at high risk of automation, while another 32% face significant changes in how they are performed.
UBI offers a promising mechanism for reducing inequality by providing individuals with a financial safety net and empowering them to pursue education, training, or entrepreneurial ventures without fear of destitution. The economic rationale behind UBI lies in its ability to redistribute wealth and ensure that the benefits of technological progress are shared more equitably.
Critiques of UBI, such as concerns about disincentivizing work, can be addressed through evidence-based arguments. Studies conducted in countries that have implemented UBI pilots, such as Finland and Canada, have shown mixed but generally positive results. Participants reported improved mental well-being, increased job satisfaction, and greater flexibility in pursuing non-traditional forms of employment.
The wealth generated by AI can be harnessed to fund UBI programs, creating a virtuous cycle of innovation, redistribution, and economic stability. Advanced AI technologies, capable of self-learning and automating complex tasks, have the potential to generate significant economic output and increase overall productivity.
Moreover, the idea of AI-generated revenue as a communal resource aligns with the concept of AI as a public good. By recognizing the collective benefits of AI advancements, policymakers can explore innovative funding mechanisms, such as taxation on AI-generated profits or revenue-sharing agreements between technology companies and governments.
Implementing UBI funded by AI-generated revenue poses several challenges, including global disparities in AI adoption and regulatory frameworks, as well as political and logistical hurdles at the national level. Addressing these challenges requires international cooperation, ethical considerations, and forward-thinking policy frameworks.
Global Disparities: The benefits of AI are unevenly distributed across countries, with developed nations having greater access to AI technologies and expertise. Ensuring fair distribution of AI benefits and UBI requires collaboration between governments, multinational organizations, and technology providers.
Policy Challenges: Designing and implementing UBI policies involves complex decision-making processes, including determining the level of basic income, funding sources, and eligibility criteria. Political will, public support, and robust governance mechanisms are essential for the successful implementation of UBI initiatives.
In conclusion, AI has the potential to be a transformative force for good, but its benefits must be shared equitably to mitigate socio-economic inequalities. By making AI a public good through Universal Basic Income, we can address the negative impacts of inequality and job displacement while harnessing the full potential of AI for societal progress. This requires bold policy changes, international cooperation, and a reimagining of our social and economic structures to ensure a more inclusive and sustainable future.
I urge policymakers, researchers, and advocates to prioritize the exploration and implementation of UBI funded by AI-generated revenue. This includes conducting further research, engaging stakeholders in meaningful dialogue, and experimenting with pilot programs to test the feasibility and impact of UBI in different contexts. Together, we can shape a future where AI serves as a catalyst for positive social change and shared prosperity."""


chrome_options = Options()

chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-web-security')
chrome_options.add_argument('--allow-running-insecure-content')

driver = webdriver.Chrome(options=chrome_options)
driver.get(googledoc_link)

# a = driver.find_element(By.CSS_SELECTOR, "canvas.kix-canvas-tile-content")

writer = ActionChains(driver)

sleep(10)


text = [t.split(' ') for t in TEXT.split('\n')]

for abstract in text:
    for word in abstract:
        sleep(10 * min(random(), 0.2))
        for char in word:
            sleep(3 * min(random(), 0.05))
            writer.send_keys(char).perform()
        writer.send_keys(' ').perform()

    # writer.key_down(Keys.SHIFT).key_down(Keys.ENTER).key_up(Keys.SHIFT).key_up(Keys.ENTER).perform()
    writer.key_down(Keys.ENTER).perform()
    sleep(3 * 60 * min(random(), 0.1))
